version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: taskmanager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
      # 5433 (your computer) -> 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: