spring.application.name=taskmanagement

# # H2 Database Configuration
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=  
# # empty password

# # JPA
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update

# # Enable H2 console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# PostgreSQL configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
#for docker
spring.datasource.url=jdbc:postgresql://localhost:5433/task_manager
spring.datasource.username=postgres
spring.datasource.password=admin
#for dcoker
# Liquibase - mark existing DB as baselined so it doesn't re-run migrations
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=default

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#If your table already exists, Hibernate will not add new columns unless told to.
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Optional: web security workaround
# spring.h2.console.settings.web-allow-others=true


#Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

#github
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
#spring.security.oauth2.client.registration.github.scope=user:email

# ===============================
# EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

gemini.api.key=${GEMINI_API_KEY}
openweather.api.key=${OPENWEATHER_API_KEY}
SENDGRID_API_KEY=${SENDGRID_API_KEY}


# http://localhost:8080/oauth2/authorization/google
# http://localhost:8080/oauth2/authorization/github
# http://localhost:8080/swagger-ui/index.html
# http://localhost:8080/actuator/prometheus     




