--
-- PostgreSQL database dump
--

\restrict wjV7M1kBCP07PPCkTyYdUnhCBSdbrmQie8tIg70LUum53gFPULgugcLQl6guyYZ

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task (
    task_id integer NOT NULL,
    created_by_id integer NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    created_by character varying(255),
    task_name character varying(255),
    task_description character varying(255),
    task_status character varying(255),
    CONSTRAINT task_task_status_check CHECK (((task_status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.task OWNER TO postgres;

--
-- Name: task_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer DEFAULT nextval('public.users_id_seq'::regclass) NOT NULL,
    username character varying(255),
    password character varying(255),
    email character varying(255),
    provider character varying(50),
    provider_id character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
baseline	hasnath	db/changelog/db.changelog-master.yaml	2026-03-30 11:20:56.159132	1	EXECUTED	9:d41d8cd98f00b204e9800998ecf8427e	empty		\N	4.31.1	\N	\N	4848055429
create-initial-tables	hasnath	db/changelog/001-initial-schema.yaml	2026-03-30 11:20:56.212042	2	EXECUTED	9:3177f9f27832352a97a5a70d227f695a	createSequence sequenceName=users_id_seq; createTable tableName=users; createTable tableName=task; sql		\N	4.31.1	\N	\N	4848055429
add-oauth-columns-to-users	hasnath	db/changelog/002-users-table-github-login.yaml	2026-03-30 11:20:56.235855	3	EXECUTED	9:ab14ca495744a0f92a88d05e01782528	addColumn tableName=users; addUniqueConstraint constraintName=uk_users_email, tableName=users		\N	4.31.1	\N	\N	4848055429
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.task (task_id, created_by_id, created_at, updated_at, created_by, task_name, task_description, task_status) FROM stdin;
11	1	2026-02-07 12:48:46.260712	2026-02-07 12:48:46.260756	navin	Sleeping	Sleeping At home	IN_PROGRESS
12	2	2026-02-09 12:18:05.678188	2026-02-09 12:18:05.678238	sushil	Coffee	I need a Coffee	PENDING
13	2	2026-02-10 11:56:58.761611	2026-02-10 11:56:58.76163	sushil	Cycling101	Updated description101	PENDING
14	5	2026-02-16 11:31:20.648715	2026-02-16 11:31:20.648886	cod	Fix login bug	Fix the login functionality that is currently broken	PENDING
15	5	2026-02-19 14:52:21.308493	2026-02-19 14:52:21.308579	cod	Iftr	You should do iftar	PENDING
16	5	2026-02-25 12:02:17.716483	2026-02-25 12:02:17.716565	cod	\N	\N	\N
17	5	2026-02-25 12:08:22.078278	2026-02-25 12:08:22.078441	cod	Fix login bug	Fix the login functionality that is currently broken	PENDING
18	5	2026-02-25 12:10:30.57108	2026-02-25 12:10:30.571196	cod	Implement OAuth	do the oauth implementation	DONE
19	5	2026-02-25 12:11:21.724968	2026-02-25 12:11:21.72509	cod	Refactor service	do Refactor service	PENDING
20	5	2026-02-25 12:12:14.645397	2026-02-25 12:12:14.645474	cod	Database optimization	do Database Optimization	IN_PROGRESS
21	5	2026-02-25 12:13:16.704219	2026-02-25 12:13:16.704409	cod	Add logging	do Database Optimization	IN_PROGRESS
22	3	2026-02-25 12:15:44.911879	2026-02-25 12:15:44.911963	hasnath	Update README	Do Update README	IN_PROGRESS
23	3	2026-02-25 12:16:17.876091	2026-02-25 12:16:17.876167	hasnath	Write unit tests	Do Write unit tests	DONE
24	3	2026-02-25 12:16:57.717241	2026-02-25 12:16:57.717374	hasnath	Setup CI/CD	Do Setup CI/CD	DONE
25	3	2026-02-25 12:17:26.089674	2026-02-25 12:17:26.089759	hasnath	Fix UI alignment	Do Fix UI alignmentfor the login page	DONE
26	3	2026-02-25 12:17:55.961796	2026-02-25 12:17:55.96187	hasnath	Performance testing	Do Performance testing	DONE
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, email, provider, provider_id) FROM stdin;
1	navin	{noop}n@123	\N	\N	\N
2	sushil	{noop}s@123	\N	\N	\N
3	hasnath	$2a$12$hNpEa0geE5C1hk/wUXbTheM7AoDetgL.zZOmvUUcG.75B.Fb37XRG	\N	\N	\N
4	avni	$2a$12$wqiwCdRXC2z7YB6iCWbPL.fEvFeZk5vS.oMuyz3hw2mp/y6GvLRvi	\N	\N	\N
5	cod	$2a$12$7xEWTYHMa/7L0x/rCioU5uAmdBVV83j0lNfn//Fjj3/f/iAJSbP3a	\N	\N	\N
6	User6	$2a$12$1rIdzeuRQ2k58A.ef8hNxujSv17lA9VZlaKXgLGloaLluXK0hAGau	\N	\N	\N
7	User7	$2a$12$tWVT3xmzu/FzC3PIb4Ef0OilCBdz7GkE5ISMsVQL83GdfqA7MTqUK	\N	\N	\N
8	abu112bakr	\N	\N	OAUTH2_USER	59804514
9	abu.hasnath@gigatechltd.com	\N	abu.hasnath@gigatechltd.com	OIDC_USER	114241313516926858762
\.


--
-- Name: task_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.task_task_id_seq', 26, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 9, true);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (task_id);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict wjV7M1kBCP07PPCkTyYdUnhCBSdbrmQie8tIg70LUum53gFPULgugcLQl6guyYZ

